import type { NextPage } from 'next';
import { useSession } from 'next-auth/react';
import Head from 'next/head';

const Home: NextPage = () => {
  const {data, status} = useSession();

  return (
    <>
      <Head>
        <title>Avante-Garde</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Data: {JSON.stringify(data)}
        Status: {status}
      </div>
    </>
  );
};

export default Home;
