import { Button, Flex, Heading } from '@chakra-ui/react';
import type { GetServerSideProps, NextPage } from 'next';
import { getSession, signOut } from 'next-auth/react';
import Head from 'next/head';
import { IUser } from '../@types/user';

const Home: NextPage<IUser> = (props) => {

  return (
    <>
      <Head>
        <title>Avante-Garde</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex w={'100vw'} h={'100vh'} bgColor={'gray.600'} justify={'center'} align={'center'}>
        <Flex w={'lg'} h={'xs'} flexDir={'column'} align={'center'} justify={'space-around'}>
          <Heading color={'gray.100'}>
            Welcome {props.name}
          </Heading>
          <Button onClick={() => {
            signOut();
          }}>
            Log out
          </Button>
        </Flex>
      </Flex>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);

  const user = session?.user;

  if(!user) {
    return {
      redirect: {
        destination: '/login',
        permanent: false
      }
    };
  }
  return {
    props: {
      ...user
    }
  };
};

export default Home;
