import { Flex, Spinner } from '@chakra-ui/react';
import axios from 'axios';
import type { GetServerSideProps, NextPage } from 'next';
import { getSession } from 'next-auth/react';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { ICard } from '../@types/card';
import { IUser } from '../@types/user';
import { AppBar } from '../components/AppBar';
import { TaskCard } from '../components/TaskCard';

const Home: NextPage<IUser> = (props) => {

  const [tasks, setTasks] = useState<ICard[] | null>(null);

  useEffect(() => {
    getCards();
  });

  const getCards = async () => {
    const response =  await axios.get('/api/card');

    const data = response.data;

    setTasks(data);
  };

  return (
    <>
      <Head>
        <title>Avante-Garde</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar></AppBar>
      <Flex w={'100vw'} h={'calc(100vh - 70px)'} bgColor={'gray.600'} justify={'center'} align={'center'}>
        <Flex w={'60%'} h={'80%'} flexDir={'column'} align={'stretch'} bgColor={'gray.800'} borderRadius={'lg'} overflowY={'scroll'}>
          {
            tasks === null ? <Spinner /> : tasks.map(task => <TaskCard key={task.id} task={task}/>)
          }
        </Flex>
      </Flex>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);

  const user = session?.user;

  if(!user) {
    return {
      redirect: {
        destination: '/login',
        permanent: false
      }
    };
  }
  return {
    props: {
      ...user
    }
  };
};

export default Home;
